
version: 0.0
os: linux
files:
  - source: /
    destination: /var/api/
hooks:
  BeforeInstall:
    -   location: scripts/install_dependencies.sh
        runas: root
        timeout: 300
  BeforeAllowTraffic:
    - location: scripts/start.sh
      runas: root
      timeout: 60
#   BeforeAllowTraffic:
#     - location: infrastructures/beforeAllowTraffic.sh
#       runas: root
#       timeout: 60
