
version: 0.0
os: linux
files:
  - source: /
    destination: /var/api/
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      runas: root
      timeout: 60
  BeforeInstall:
    -   location: scripts/copy_source_code.sh
        runas: root
        timeout: 300  
  ApplicationStart:
    - location: scripts/start_server.sh
      runas: root
      timeout: 60
#   BeforeAllowTraffic:
#     - location: infrastructures/beforeAllowTraffic.sh
#       runas: root
#       timeout: 60
